// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CommandResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        message_id: {
            type: 'string',
            title: 'Message Id'
        }
    },
    type: 'object',
    required: ['message', 'message_id'],
    title: 'CommandResponse'
} as const;

export const DashboardCardDataSchema = {
    properties: {
        total_users: {
            type: 'integer',
            title: 'Total Users'
        },
        total_items: {
            type: 'integer',
            title: 'Total Items'
        },
        active_users: {
            type: 'integer',
            title: 'Active Users'
        },
        inactive_items: {
            type: 'integer',
            title: 'Inactive Items'
        }
    },
    type: 'object',
    required: ['total_users', 'total_items', 'active_users', 'inactive_items'],
    title: 'DashboardCardData'
} as const;

export const DashboardDataSchema = {
    properties: {
        cards: {
            '$ref': '#/components/schemas/DashboardCardData'
        },
        revenue: {
            items: {
                '$ref': '#/components/schemas/RevenueData'
            },
            type: 'array',
            title: 'Revenue'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['cards', 'revenue', 'items'],
    title: 'DashboardData'
} as const;

export const DeviceInfoSchema = {
    properties: {
        device_id: {
            type: 'integer',
            title: 'Device Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        class_id: {
            type: 'integer',
            title: 'Class Id'
        },
        parent_id: {
            type: 'integer',
            title: 'Parent Id'
        },
        plant_id: {
            type: 'integer',
            title: 'Plant Id'
        }
    },
    type: 'object',
    required: ['device_id', 'name', 'class_id', 'parent_id', 'plant_id'],
    title: 'DeviceInfo'
} as const;

export const ElectricityCostRowSchema = {
    properties: {
        price_date: {
            type: 'string',
            format: 'date',
            title: 'Price Date'
        },
        hour_of_day: {
            type: 'integer',
            title: 'Hour Of Day'
        },
        price_UAH_per_MWh: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Price Uah Per Mwh'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['price_date', 'hour_of_day', 'price_UAH_per_MWh', 'id'],
    title: 'ElectricityCostRow'
} as const;

export const ExportGranularitySchema = {
    type: 'string',
    enum: ['hourly'],
    title: 'ExportGranularity'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HistoricalDataGroupedResponseSchema = {
    properties: {
        series: {
            items: {
                '$ref': '#/components/schemas/TimeSeriesData'
            },
            type: 'array',
            title: 'Series'
        }
    },
    type: 'object',
    required: ['series'],
    title: 'HistoricalDataGroupedResponse'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id', 'tenant_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            maxLength: 255,
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            maxLength: 1024,
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlantConfigResponseSchema = {
    properties: {
        tenant_id: {
            type: 'string',
            title: 'Tenant Id'
        },
        devices: {
            items: {
                '$ref': '#/components/schemas/DeviceInfo'
            },
            type: 'array',
            title: 'Devices'
        }
    },
    type: 'object',
    required: ['tenant_id', 'devices'],
    title: 'PlantConfigResponse'
} as const;

export const PlcDataControlExtendedRowSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        plant_id: {
            type: 'integer',
            title: 'Plant Id'
        },
        control_type: {
            type: 'integer',
            title: 'Control Type'
        },
        data_id: {
            type: 'integer',
            title: 'Data Id'
        },
        data_id_txt: {
            type: 'integer',
            title: 'Data Id Txt'
        },
        data: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By'
        },
        device_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Text'
        },
        data_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Text'
        },
        input_type: {
            type: 'string',
            title: 'Input Type'
        },
        textlist_entries: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Textlist Entries'
        }
    },
    type: 'object',
    required: ['id', 'plant_id', 'control_type', 'data_id', 'data_id_txt', 'data', 'updated_at', 'updated_by', 'device_text', 'data_text', 'input_type'],
    title: 'PlcDataControlExtendedRow'
} as const;

export const PlcDataSettingsExtendedRowSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        plant_id: {
            type: 'integer',
            title: 'Plant Id'
        },
        device_id: {
            type: 'integer',
            title: 'Device Id'
        },
        data_id: {
            type: 'integer',
            title: 'Data Id'
        },
        data: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By'
        },
        device_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Text'
        },
        data_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Text'
        },
        input_type: {
            type: 'string',
            title: 'Input Type'
        },
        textlist_entries: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Textlist Entries'
        }
    },
    type: 'object',
    required: ['id', 'plant_id', 'device_id', 'data_id', 'data', 'updated_at', 'updated_by', 'device_text', 'data_text', 'input_type'],
    title: 'PlcDataSettingsExtendedRow'
} as const;

export const PlcDataSettingsUpdateSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        data: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'PlcDataSettingsUpdate'
} as const;

export const PrivateUserCreateInputSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'PrivateUserCreateInput'
} as const;

export const RealtimeDataPointSchema = {
    properties: {
        data_id: {
            type: 'integer',
            title: 'Data Id'
        },
        plant_id: {
            type: 'integer',
            title: 'Plant Id'
        },
        device_id: {
            type: 'integer',
            title: 'Device Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        timestamp: {
            type: 'integer',
            title: 'Timestamp'
        },
        value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        }
    },
    type: 'object',
    required: ['data_id', 'plant_id', 'device_id', 'name', 'timestamp'],
    title: 'RealtimeDataPoint'
} as const;

export const RealtimeDataResponseSchema = {
    properties: {
        values: {
            items: {
                '$ref': '#/components/schemas/RealtimeDataPoint'
            },
            type: 'array',
            title: 'Values'
        }
    },
    type: 'object',
    required: ['values'],
    title: 'RealtimeDataResponse'
} as const;

export const RevenueDataSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        revenue: {
            type: 'integer',
            title: 'Revenue'
        }
    },
    type: 'object',
    required: ['month', 'revenue'],
    title: 'RevenueData'
} as const;

export const ScheduleRowSchema = {
    properties: {
        rec_no: {
            type: 'integer',
            title: 'Rec No'
        },
        start_time: {
            type: 'string',
            format: 'time',
            title: 'Start Time'
        },
        charge_from_grid: {
            type: 'boolean',
            title: 'Charge From Grid'
        },
        allow_to_sell: {
            type: 'boolean',
            title: 'Allow To Sell'
        },
        charge_power: {
            type: 'number',
            title: 'Charge Power'
        },
        charge_limit: {
            type: 'number',
            title: 'Charge Limit'
        },
        discharge_power: {
            type: 'number',
            title: 'Discharge Power'
        },
        source: {
            type: 'integer',
            title: 'Source'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        updated_by: {
            type: 'string',
            title: 'Updated By'
        }
    },
    type: 'object',
    required: ['rec_no', 'start_time', 'charge_from_grid', 'allow_to_sell', 'charge_power', 'charge_limit', 'discharge_power', 'source', 'id', 'updated_at', 'updated_by'],
    title: 'ScheduleRow'
} as const;

export const TenantCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        plant_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plant Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TenantCreate'
} as const;

export const TenantPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        plant_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plant Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'TenantPublic'
} as const;

export const TenantUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        plant_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plant Id'
        }
    },
    type: 'object',
    title: 'TenantUpdate'
} as const;

export const TenantsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TenantPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TenantsPublic'
} as const;

export const TimeSeriesDataSchema = {
    properties: {
        data_id: {
            type: 'integer',
            title: 'Data Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        data: {
            items: {
                '$ref': '#/components/schemas/TimeSeriesPoint'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data_id', 'name', 'data'],
    title: 'TimeSeriesData'
} as const;

export const TimeSeriesPointSchema = {
    properties: {
        x: {
            type: 'integer',
            title: 'X'
        },
        y: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Y'
        }
    },
    type: 'object',
    required: ['x', 'y'],
    title: 'TimeSeriesPoint'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            maxLength: 1024,
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role',
            default: 'client'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        }
    },
    type: 'object',
    required: ['email', 'password', 'tenant_id'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            type: 'string',
            maxLength: 50,
            title: 'Role',
            default: 'client'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        }
    },
    type: 'object',
    required: ['email', 'id', 'tenant_id'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        tenant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Id'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;