// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommandResponse = {
    message: string;
    message_id: string;
};

export type DashboardCardData = {
    total_users: number;
    total_items: number;
    active_users: number;
    inactive_items: number;
};

export type DashboardData = {
    cards: DashboardCardData;
    revenue: Array<RevenueData>;
    items: Array<ItemPublic>;
};

export type DeviceInfo = {
    device_id: number;
    name: string;
    class_id: number;
    parent_id: number;
    plant_id: number;
};

export type ElectricityCostRow = {
    price_date: string;
    hour_of_day: number;
    price_UAH_per_MWh: string;
    received_at?: (string | null);
    id: number;
};

export type ExportGranularity = 'hourly';

export type HistoricalDataGroupedResponse = {
    series: Array<TimeSeriesData>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    tenant_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PlantConfigResponse = {
    tenant_id: string;
    devices: Array<DeviceInfo>;
};

export type PlcDataControlExtendedRow = {
    id: number;
    plant_id: number;
    control_type: number;
    data_id: number;
    data_id_txt: number;
    data: (number | null);
    updated_at: (string | null);
    updated_by: (string | null);
    device_text: (string | null);
    data_text: (string | null);
    input_type: string;
    textlist_entries?: ({
    [key: string]: string;
} | null);
};

export type PlcDataSettingsExtendedRow = {
    id: number;
    plant_id: number;
    device_id: number;
    data_id: number;
    data: (number | null);
    updated_at: (string | null);
    updated_by: (string | null);
    device_text: (string | null);
    data_text: (string | null);
    input_type: string;
    textlist_entries?: ({
    [key: string]: string;
} | null);
};

export type PlcDataSettingsUpdate = {
    id: number;
    data?: (number | null);
    updated_by?: (string | null);
};

export type PrivateUserCreateInput = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type RealtimeDataPoint = {
    data_id: number;
    plant_id: number;
    device_id: number;
    name: string;
    timestamp: number;
    value?: (string | number | null);
};

export type RealtimeDataResponse = {
    values: Array<RealtimeDataPoint>;
};

export type RevenueData = {
    month: string;
    revenue: number;
};

export type ScheduleRow = {
    rec_no: number;
    start_time: string;
    charge_from_grid: boolean;
    allow_to_sell: boolean;
    charge_power: number;
    charge_limit: number;
    discharge_power: number;
    source: number;
    id: number;
    updated_at: string;
    updated_by: string;
};

export type TenantCreate = {
    name: string;
    description?: (string | null);
    plant_id?: (number | null);
};

export type TenantPublic = {
    name: string;
    description?: (string | null);
    plant_id?: (number | null);
    id: string;
};

export type TenantsPublic = {
    data: Array<TenantPublic>;
    count: number;
};

export type TenantUpdate = {
    name?: (string | null);
    description?: (string | null);
    plant_id?: (number | null);
};

export type TimeSeriesData = {
    data_id: number;
    name: string;
    data: Array<TimeSeriesPoint>;
};

export type TimeSeriesPoint = {
    x: number;
    y: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (string | null);
    password: string;
    tenant_id: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: string;
    id: string;
    tenant_id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    role?: (string | null);
    tenant_id?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ControlGetPlcControlData = {
    /**
     * Optional list of CONTROL_TYPEs to fetch
     */
    controlTypes?: Array<number>;
    /**
     * Optional list of PLANT_IDs to fetch
     */
    plantIds?: Array<number>;
    /**
     * Tenant ID to fetch data for
     */
    tenantId: string;
};

export type ControlGetPlcControlResponse = (Array<PlcDataControlExtendedRow>);

export type ControlUpdatePlcControlData = {
    requestBody: Array<PlcDataSettingsUpdate>;
    /**
     * Tenant ID to update control for
     */
    tenantId: string;
};

export type ControlUpdatePlcControlResponse = (CommandResponse);

export type DashboardReadDashboardDataData = {
    /**
     * Admin override to view a specific tenant's dashboard
     */
    tenantIdOverride?: (string | null);
};

export type DashboardReadDashboardDataResponse = (DashboardData);

export type DefaultGetPlantConfigData = {
    /**
     * Optional list of DEVICE_IDs to fetch
     */
    deviceIds?: Array<number>;
    /**
     * Tenant ID to fetch data for
     */
    tenantId: string;
};

export type DefaultGetPlantConfigResponse = (PlantConfigResponse);

export type ElectricityCostReadElectricityCostData = {
    /**
     * Date (YYYY-MM-DD)
     */
    date: string;
    /**
     * Tenant ID to fetch electricity cost for
     */
    tenantId: string;
};

export type ElectricityCostReadElectricityCostResponse = (Array<ElectricityCostRow>);

export type HistoricalDataReadHistoricalDetailsData = {
    /**
     * Aggregation level: hour (raw data), day, month, year (deltas)
     */
    aggregateBy?: ('hour' | 'day' | 'month' | 'year' | null);
    /**
     * List of DATA_IDs to fetch
     */
    dataIds: Array<number>;
    /**
     * End timestamp
     */
    end?: (string | null);
    /**
     * Start timestamp
     */
    start?: (string | null);
    /**
     * Tenant ID to fetch data for
     */
    tenantId: string;
};

export type HistoricalDataReadHistoricalDetailsResponse = (HistoricalDataGroupedResponse);

export type HistoricalDataExportHistoricalDataData = {
    /**
     * End timestamp (local time)
     */
    end?: (string | null);
    /**
     * Granularity for exported data (e..g, 'hourly')
     */
    exportGranularity: ExportGranularity;
    /**
     * Start timestamp (local time)
     */
    start?: (string | null);
    /**
     * Tenant ID for plant lookup
     */
    tenantId: string;
};

export type HistoricalDataExportHistoricalDataResponse = (HistoricalDataGroupedResponse);

export type ItemsReadItemsData = {
    /**
     * Fetch items from all tenants (Superuser only)
     */
    allTenants?: boolean;
    limit?: number;
    skip?: number;
    /**
     * Filter by specific tenant ID (Superuser only)
     */
    tenantId?: (string | null);
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlantsReadPlantByIdData = {
    plantId: number;
};

export type PlantsReadPlantByIdResponse = (unknown);

export type PlantsUpdatePlantData = {
    plantId: number;
    requestBody: {
        [key: string]: unknown;
    };
};

export type PlantsUpdatePlantResponse = (unknown);

export type PlantsDeletePlantData = {
    plantId: number;
};

export type PlantsDeletePlantResponse = (unknown);

export type PlantsReadAllPlantsData = {
    limit?: number;
    skip?: number;
};

export type PlantsReadAllPlantsResponse = (unknown);

export type PlantsCreatePlantData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type PlantsCreatePlantResponse = (unknown);

export type PrivateCreateUserWithNewTenantData = {
    requestBody: PrivateUserCreateInput;
};

export type PrivateCreateUserWithNewTenantResponse = (UserPublic);

export type RealtimeDataReadRealtimeLatestData = {
    /**
     * List of DATA_IDs to filter by (optional)
     */
    dataIds?: Array<number>;
    /**
     * List of DEVICE_IDs to fetch
     */
    deviceIds: Array<number>;
    /**
     * Tenant ID to fetch data for
     */
    tenantId: string;
};

export type RealtimeDataReadRealtimeLatestResponse = (RealtimeDataResponse);

export type ScheduleReadScheduleData = {
    /**
     * Date (YYYY-MM-DD)
     */
    date: string;
    /**
     * Tenant ID to fetch schedule for
     */
    tenantId: string;
};

export type ScheduleReadScheduleResponse = (Array<ScheduleRow>);

export type ScheduleBulkUpdateScheduleData = {
    date: string;
    requestBody: Array<ScheduleRow>;
    /**
     * Tenant ID to update schedule for
     */
    tenantId: string;
};

export type ScheduleBulkUpdateScheduleResponse = (CommandResponse);

export type SettingsGetPlcDataSettingsData = {
    /**
     * Optional list of DEVICE_IDs to fetch
     */
    deviceIds?: Array<number>;
    /**
     * Optional list of PLANT_IDs to fetch
     */
    plantIds?: Array<number>;
    /**
     * Tenant ID to fetch data for
     */
    tenantId: string;
};

export type SettingsGetPlcDataSettingsResponse = (Array<PlcDataSettingsExtendedRow>);

export type SettingsUpdatePlcDataSettingsData = {
    requestBody: Array<PlcDataSettingsUpdate>;
    /**
     * Tenant ID to update settings for
     */
    tenantId: string;
};

export type SettingsUpdatePlcDataSettingsResponse = (CommandResponse);

export type TenantsCreateTenantData = {
    requestBody: TenantCreate;
};

export type TenantsCreateTenantResponse = (TenantPublic);

export type TenantsReadTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsReadTenantsResponse = (TenantsPublic);

export type TenantsReadTenantByIdData = {
    tenantId: string;
};

export type TenantsReadTenantByIdResponse = (TenantPublic);

export type TenantsUpdateTenantData = {
    requestBody: TenantUpdate;
    tenantId: string;
};

export type TenantsUpdateTenantResponse = (TenantPublic);

export type TenantsDeleteTenantData = {
    tenantId: string;
};

export type TenantsDeleteTenantResponse = (Message);

export type UsersReadUsersData = {
    /**
     * Fetch users from all tenants (Superuser only)
     */
    allTenants?: boolean;
    limit?: number;
    skip?: number;
    /**
     * Filter by specific tenant ID (Superuser only)
     */
    tenantId?: (string | null);
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsWebhookPullResponse = (unknown);

export type UtilsHealthCheckResponse = (boolean);