"""Add column plant_id to tenant model

Revision ID: b2dbb0f10f30
Revises: 2af7a923bc9f
Create Date: 2025-10-29 15:25:00.009912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b2dbb0f10f30'
down_revision = '2af7a923bc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tenant_plant_id'), 'tenant', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_plant_id'), table_name='tenant')
    op.drop_column('tenant', 'plant_id')
    # ### end Alembic commands ###
