"""dd tenant models and relationships

Revision ID: e1407462495c
Revises: 1a31ce608336
Create Date: 2025-10-20 11:38:20.154514

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import uuid  # <-- IMPORT ADDED


# revision identifiers, used by Alembic.
revision = 'e1407462495c'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


#Define table specs for data migration
tenant_table = sa.table(
    'tenant',
    sa.column('id', sa.Uuid),
    sa.column('name', sa.String),
    sa.column('description', sa.String),
)
user_table = sa.table('user', sa.column('tenant_id', sa.Uuid))
item_table = sa.table('item', sa.column('tenant_id', sa.Uuid))

# Generate a static UUID for the default tenant
DEFAULT_TENANT_ID_OBJ = uuid.uuid4()  # <--- FIX: Generate the UUID object


def upgrade():
    # ### commands auto generated by Alembic - MANUALLY ADJUSTED! ###

    # 1. Create the tenant table
    op.create_table('tenant',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False, default=sa.text('uuid_generate_v4()') if op.get_bind().dialect.name == 'postgresql' else None),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)

    # 2. Add tenant_id columns as NULLABLE (temporarily)
    op.add_column('item', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('tenant_id', sa.Uuid(), nullable=True))

    # 3. Create a Default Tenant for existing data
    op.bulk_insert(
        tenant_table,
        [
            {
                'id': DEFAULT_TENANT_ID_OBJ,  # <--- FIX: Pass the UUID object
                'name': 'Default Tenant',
                'description': 'Default tenant for data created before multi-tenancy was implemented.',
            }
        ],
    )

    # 4. Update all existing users and items to belong to the Default Tenant
    op.execute(
        user_table.update()
        .where(user_table.c.tenant_id == None)
        .values(tenant_id=DEFAULT_TENANT_ID_OBJ)  # <--- FIX: Pass the UUID object
    )
    op.execute(
        item_table.update()
        .where(item_table.c.tenant_id == None)
        .values(tenant_id=DEFAULT_TENANT_ID_OBJ)  # <--- FIX: Pass the UUID object
    )

    # 5. NOW, alter the columns to be NON-nullable
    op.alter_column('user', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.alter_column('item', 'tenant_id', existing_type=sa.Uuid(), nullable=False)

    # 6. Create foreign keys
    op.drop_constraint(op.f('item_owner_id_fkey'), 'item', type_='foreignkey') # Autogen line
    op.create_foreign_key('fk_item_tenant_id', 'item', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key('fk_item_owner_id', 'item', 'user', ['owner_id'], ['id'])
    op.create_foreign_key('fk_user_tenant_id', 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - MANUALLY ADJUSTED! ###
    
    # 1. Drop foreign keys
    op.drop_constraint('fk_user_tenant_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_item_owner_id', 'item', type_='foreignkey')
    op.drop_constraint('fk_item_tenant_id', 'item', type_='foreignkey')
    
    # 2. Recreate old item FK
    op.create_foreign_key(op.f('item_owner_id_fkey'), 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    # 3. Drop columns
    op.drop_column('user', 'tenant_id')
    op.drop_column('item', 'tenant_id')

    # 4. Drop tenant table
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###