/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUzeRouteImport } from './routes/_layout/uze'
import { Route as LayoutTenantRouteImport } from './routes/_layout/tenant'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSesRouteImport } from './routes/_layout/ses'
import { Route as LayoutScheduleRouteImport } from './routes/_layout/schedule'
import { Route as LayoutResetPasswordRouteImport } from './routes/_layout/reset-password'
import { Route as LayoutRecoverPasswordRouteImport } from './routes/_layout/recover-password'
import { Route as LayoutPlantSettingsRouteImport } from './routes/_layout/plant-settings'
import { Route as LayoutPlantManagementRouteImport } from './routes/_layout/plant-management'
import { Route as LayoutPlantRouteImport } from './routes/_layout/plant'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutControlRouteImport } from './routes/_layout/control'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPlantPlantIdRouteImport } from './routes/_layout/plant_/$plantId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUzeRoute = LayoutUzeRouteImport.update({
  id: '/uze',
  path: '/uze',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantRoute = LayoutTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSesRoute = LayoutSesRouteImport.update({
  id: '/ses',
  path: '/ses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScheduleRoute = LayoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResetPasswordRoute = LayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecoverPasswordRoute = LayoutRecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlantSettingsRoute = LayoutPlantSettingsRouteImport.update({
  id: '/plant-settings',
  path: '/plant-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlantManagementRoute = LayoutPlantManagementRouteImport.update({
  id: '/plant-management',
  path: '/plant-management',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlantRoute = LayoutPlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutControlRoute = LayoutControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlantPlantIdRoute = LayoutPlantPlantIdRouteImport.update({
  id: '/plant_/$plantId',
  path: '/plant/$plantId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof LayoutAdminRoute
  '/control': typeof LayoutControlRoute
  '/login': typeof LayoutLoginRoute
  '/plant': typeof LayoutPlantRoute
  '/plant-management': typeof LayoutPlantManagementRoute
  '/plant-settings': typeof LayoutPlantSettingsRoute
  '/recover-password': typeof LayoutRecoverPasswordRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/schedule': typeof LayoutScheduleRoute
  '/ses': typeof LayoutSesRoute
  '/settings': typeof LayoutSettingsRoute
  '/tenant': typeof LayoutTenantRoute
  '/uze': typeof LayoutUzeRoute
  '/': typeof LayoutIndexRoute
  '/plant/$plantId': typeof LayoutPlantPlantIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof LayoutAdminRoute
  '/control': typeof LayoutControlRoute
  '/login': typeof LayoutLoginRoute
  '/plant': typeof LayoutPlantRoute
  '/plant-management': typeof LayoutPlantManagementRoute
  '/plant-settings': typeof LayoutPlantSettingsRoute
  '/recover-password': typeof LayoutRecoverPasswordRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/schedule': typeof LayoutScheduleRoute
  '/ses': typeof LayoutSesRoute
  '/settings': typeof LayoutSettingsRoute
  '/tenant': typeof LayoutTenantRoute
  '/uze': typeof LayoutUzeRoute
  '/': typeof LayoutIndexRoute
  '/plant/$plantId': typeof LayoutPlantPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/control': typeof LayoutControlRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/plant': typeof LayoutPlantRoute
  '/_layout/plant-management': typeof LayoutPlantManagementRoute
  '/_layout/plant-settings': typeof LayoutPlantSettingsRoute
  '/_layout/recover-password': typeof LayoutRecoverPasswordRoute
  '/_layout/reset-password': typeof LayoutResetPasswordRoute
  '/_layout/schedule': typeof LayoutScheduleRoute
  '/_layout/ses': typeof LayoutSesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tenant': typeof LayoutTenantRoute
  '/_layout/uze': typeof LayoutUzeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/plant_/$plantId': typeof LayoutPlantPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/control'
    | '/login'
    | '/plant'
    | '/plant-management'
    | '/plant-settings'
    | '/recover-password'
    | '/reset-password'
    | '/schedule'
    | '/ses'
    | '/settings'
    | '/tenant'
    | '/uze'
    | '/'
    | '/plant/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/control'
    | '/login'
    | '/plant'
    | '/plant-management'
    | '/plant-settings'
    | '/recover-password'
    | '/reset-password'
    | '/schedule'
    | '/ses'
    | '/settings'
    | '/tenant'
    | '/uze'
    | '/'
    | '/plant/$plantId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/admin'
    | '/_layout/control'
    | '/_layout/login'
    | '/_layout/plant'
    | '/_layout/plant-management'
    | '/_layout/plant-settings'
    | '/_layout/recover-password'
    | '/_layout/reset-password'
    | '/_layout/schedule'
    | '/_layout/ses'
    | '/_layout/settings'
    | '/_layout/tenant'
    | '/_layout/uze'
    | '/_layout/'
    | '/_layout/plant_/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/uze': {
      id: '/_layout/uze'
      path: '/uze'
      fullPath: '/uze'
      preLoaderRoute: typeof LayoutUzeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenant': {
      id: '/_layout/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof LayoutTenantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ses': {
      id: '/_layout/ses'
      path: '/ses'
      fullPath: '/ses'
      preLoaderRoute: typeof LayoutSesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schedule': {
      id: '/_layout/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof LayoutScheduleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reset-password': {
      id: '/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LayoutResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recover-password': {
      id: '/_layout/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof LayoutRecoverPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plant-settings': {
      id: '/_layout/plant-settings'
      path: '/plant-settings'
      fullPath: '/plant-settings'
      preLoaderRoute: typeof LayoutPlantSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plant-management': {
      id: '/_layout/plant-management'
      path: '/plant-management'
      fullPath: '/plant-management'
      preLoaderRoute: typeof LayoutPlantManagementRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plant': {
      id: '/_layout/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof LayoutPlantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/control': {
      id: '/_layout/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof LayoutControlRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plant_/$plantId': {
      id: '/_layout/plant_/$plantId'
      path: '/plant/$plantId'
      fullPath: '/plant/$plantId'
      preLoaderRoute: typeof LayoutPlantPlantIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutControlRoute: typeof LayoutControlRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutPlantRoute: typeof LayoutPlantRoute
  LayoutPlantManagementRoute: typeof LayoutPlantManagementRoute
  LayoutPlantSettingsRoute: typeof LayoutPlantSettingsRoute
  LayoutRecoverPasswordRoute: typeof LayoutRecoverPasswordRoute
  LayoutResetPasswordRoute: typeof LayoutResetPasswordRoute
  LayoutScheduleRoute: typeof LayoutScheduleRoute
  LayoutSesRoute: typeof LayoutSesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTenantRoute: typeof LayoutTenantRoute
  LayoutUzeRoute: typeof LayoutUzeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPlantPlantIdRoute: typeof LayoutPlantPlantIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutControlRoute: LayoutControlRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutPlantRoute: LayoutPlantRoute,
  LayoutPlantManagementRoute: LayoutPlantManagementRoute,
  LayoutPlantSettingsRoute: LayoutPlantSettingsRoute,
  LayoutRecoverPasswordRoute: LayoutRecoverPasswordRoute,
  LayoutResetPasswordRoute: LayoutResetPasswordRoute,
  LayoutScheduleRoute: LayoutScheduleRoute,
  LayoutSesRoute: LayoutSesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTenantRoute: LayoutTenantRoute,
  LayoutUzeRoute: LayoutUzeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPlantPlantIdRoute: LayoutPlantPlantIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
